trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'function-event-hub-processor - BUILD'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'Demo Account'
  region: 'East US'
  resourceGroupName: 'rutzsco-demo-event-processor'
  functionAppName: 'rutzsco-demo-event-processor'  
stages:
 - stage: CI
   displayName: CI stage 
  
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: $(vmImageName)   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
                       
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Ingest Event Hub - Deploy'
              inputs:
                azureResourceManagerConnection: '$(azureSubscription)'
                resourceGroupName: '$(resourceGroupName)'
                location: '$(region)'
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/event-hub.json'
                overrideParameters: '-namespaces_name "rutzsco-demo-ingest-nsp-ci" -eventhubs_name "ingest-001"'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - powershell: |
                $outputs = ConvertFrom-Json $($env:ResourceGroupDeploymentOutputs)
   
                foreach ($output in $outputs.PSObject.Properties) {
                    Write-Host "##vso[task.setvariable variable=RGDO_$($output.Name)]$($output.Value.value)"
                }
   
              displayName: 'Ingest Event Hub - Outputs copy'

            - task: AzureResourceGroupDeployment@3
              displayName: '3. Create Function Infrastructure'
              inputs:
                azureResourceManagerConnection: '$(azureSubscription)'
                resourceGroupName: '$(resourceGroupName)'
                location: '$(region)'
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/function-app-consumption.json'
                overrideParameters: '-appName $(functionAppName) -storageAccountName azfuncepci1'
                deploymentOutputs: ResourceGroupDeploymentOutputs
 
            - task: AzureFunctionApp@1
              displayName: '4. Azure functions app deploy'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: functionApp
                appName: $(functionAppName)
                package: '$(Pipeline.Workspace)/build/App/Demo.EventProcessor.zip'
                AppSettings: '-IngestEventHubConnectionString $(RGDO_NamespaceDefaultConnectionString) -SCALE_CONTROLLER_LOGGING_ENABLED AppInsights:Verbose'

            - task: AzureResourceGroupDeployment@3
              displayName: '5. Create Sender Function Infrastructure'
              inputs:
                azureResourceManagerConnection: '$(azureSubscription)'
                resourceGroupName: '$(resourceGroupName)'
                location: '$(region)'
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/function-app-consumption.json'
                overrideParameters: '-appName rutzsco-demo-event-sender -storageAccountName azfunces1'
                deploymentOutputs: ResourceGroupDeploymentOutputs
 
            - task: AzureFunctionApp@1
              displayName: '6. Azure Sender functions app deploy'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: functionApp
                appName: rutzsco-demo-event-sender
                package: '$(Pipeline.Workspace)/build/App/Demo.EventSender.zip'
                AppSettings: '-IngestEventHubConnectionString $(RGDO_NamespaceDefaultConnectionString)'